baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "cortex"
[params]
email = "waytrue@outlook.com"
footer = "Built with ♥ with Org-mode and Hugo."
repo = "https://github.com/WaytrueDeng/hugo"
entrypoint = "/posts/index"
